sudo: false
language: ruby
rvm:
  - 2.3.0
  - 2.4.0
script: "bundle exec rspec"
deploy:
  provider: rubygems
  api_key: ${RUBYGEMS_API_KEY}
  gemspec: session-validator-client.gemspec
  on:
    tags: true
